module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {},
    },
    plugins: [],
    safelist: [
        'bg-light-blue-700',
        'bg-light-blue-600',
        'bg-light-blue-500',
        'bg-light-blue-400',
        'bg-light-blue-300',
        'bg-light-blue-200',
        'bg-light-blue-100',
        'bg-light-blue-50',
        'bg-grey-50',
        'bg-orange-50',
        'bg-orange-100',
        'bg-orange-200',
        'bg-orange-300',
        'bg-orange-400',
        'bg-orange-500',
        'bg-orange-600',
        'bg-orange-700',
    ],
}
